### ISSUE TITLE
README descriptions duplicated

### ISSUE THREAD

**Issue by cfairweather** [frekele/helicopterizer#9]
The descriptions on the README for the options `GZIP_COMPRESSION` and `CLEAN_DATA_BEFORE_RESTORE` are the same. 

I imagine that this is not intentional, as the description "Boolean to indicate the compression of the file .tar to .tar.gz" make more sense for `GZIP_COMPRESSION` rather than `CLEAN_DATA_BEFORE_RESTORE`.

**Comment by frekele** [comment]
@cfairweather thank you for your contribution, I am correcting now.
